from enum import Enum

class MfaAvailabilityCheckResult(Enum):
	FAIL_BY_TOKEN_INVALID				= -5
	FAIL_BY_TOKEN_EXPIRED				= -4
	FAIL_BY_ACCESS_DENIED				= -3
	FAIL_BY_INVALID_PARAMETERS			= -2
	FAIL_BY_SERVICE_TEMPORARY_NOT_VALID	= -1
	SUCCESS								= 0

class MfaTransactionStartResult(Enum):
	FAIL_BY_TEMPLATE_NOT_FOUND			= -8
	FAIL_BY_USER_DEVICE_NOT_FOUND		= -7
	FAIL_BY_TOKEN_INVALID				= -5
	FAIL_BY_TOKEN_EXPIRED				= -4
	FAIL_BY_ACCESS_DENIED				= -3
	FAIL_BY_INVALID_PARAMETERS			= -2
	FAIL_BY_SERVICE_TEMPORARY_NOT_VALID	= -1
	SUCCESS								= 0

class MfaTransactionStatusGetResult(Enum):
	FAIL_BY_TRANSACTION_NOT_FOUND		= -6
	FAIL_BY_TOKEN_INVALID				= -5
	FAIL_BY_TOKEN_EXPIRED				= -4
	FAIL_BY_ACCESS_DENIED				= -3
	FAIL_BY_INVALID_PARAMETERS			= -2
	FAIL_BY_SERVICE_TEMPORARY_NOT_VALID	= -1
	SUCCESS								= 0

class MfaTransactionCancelResult(Enum):
	FAIL_BY_ALREADY_CANCELED			= -10
	FAIL_BY_TRANSACTION_COMPLETED		= -9
	FAIL_BY_TRANSACTION_EXPIRED			= -8
	FAIL_BY_TRANSACTION_NOT_FOUND		= -6
	FAIL_BY_TOKEN_INVALID				= -5
	FAIL_BY_TOKEN_EXPIRED				= -4
	FAIL_BY_ACCESS_DENIED				= -3
	FAIL_BY_INVALID_PARAMETERS			= -2
	FAIL_BY_SERVICE_TEMPORARY_NOT_VALID	= -1
	SUCCESS								= 0

class MfaTransactionStatus(Enum):
	PENDING 	= 0
	COMPLETED 	= 1
	EXPIRED		= 2
	CANCELED	= 4

class MfaTransactionCompleteResult(Enum):
	APPROVED = 0
	DENIED = 1