from enum import Enum

class UserDataByWalletSetResult(Enum):
	FAIL_BY_KEY_INVALID					= -8
	FAIL_BY_KEY_ACCESS_DENIED			= -7
	FAIL_BY_WALLET_NOT_EXISTS			= -6
	FAIL_BY_INVALID_PARAMETERS			= -5
	FAIL_BY_SERVICE_TEMPORARY_NOT_VALID	= -4
	FAIL_BY_ACCESS_DENIED				= -3
	FAIL_BY_TOKEN_EXPIRED				= -2
	FAIL_BY_TOKEN_INVALID				= -1
	SUCCESS								= 0

class UserDataByWalletGetResult(Enum):
	FAIL_BY_WALLET_NOT_EXISTS			= -6
	FAIL_BY_INVALID_PARAMETERS			= -5
	FAIL_BY_SERVICE_TEMPORARY_NOT_VALID	= -4
	FAIL_BY_ACCESS_DENIED				= -3
	FAIL_BY_TOKEN_EXPIRED				= -2
	FAIL_BY_TOKEN_INVALID				= -1
	SUCCESS								= 0
	SUCCESS_NOT_FOUND					= 1

class UserDataKeysByWalletGetResult(Enum):
	FAIL_BY_WALLET_NOT_EXISTS			= -6
	FAIL_BY_INVALID_PARAMETERS			= -5
	FAIL_BY_SERVICE_TEMPORARY_NOT_VALID	= -4
	FAIL_BY_ACCESS_DENIED				= -3
	FAIL_BY_TOKEN_EXPIRED				= -2
	FAIL_BY_TOKEN_INVALID				= -1
	SUCCESS								= 0
	SUCCESS_NOT_FOUND					= 1

class UserDataKeysByWalletDeleteResult(Enum):
	FAIL_BY_WALLET_NOT_EXISTS			= -6
	FAIL_BY_INVALID_PARAMETERS			= -5
	FAIL_BY_SERVICE_TEMPORARY_NOT_VALID	= -4
	FAIL_BY_ACCESS_DENIED				= -3
	FAIL_BY_TOKEN_EXPIRED				= -2
	FAIL_BY_TOKEN_INVALID				= -1
	SUCCESS								= 0
	SUCCESS_NOT_FOUND					= 1