from enum import Enum

class KycUserStatus(Enum):
	NONE					= 0
	PENDING					= 1
	COMPLETE_SUCCESS		= 2
	COMPLETE_FAIL_RETRYABLE	= 3
	COMPLETE_FAIL_FINAL		= 4
	DELETED					= 5

class KycUserStatusGetResult(Enum):
	FAIL_BY_USER_KYC_DELETED			= -8
	FAIL_BY_USER_NOT_FOUND				= -7
	FAIL_BY_BILLING						= -6
	FAIL_BY_INVALID_PARAMETERS			= -5
	FAIL_BY_SERVICE_TEMPORARY_NOT_VALID	= -4
	FAIL_BY_ACCESS_DENIED				= -3
	FAIL_BY_TOKEN_EXPIRED				= -2
	FAIL_BY_TOKEN_INVALID				= -1
	SUCCESS								= 0

class KycUserStatusTopLevelGetResult(Enum):
	FAIL_BY_INVALID_PARAMETERS			= -7
	FAIL_BY_USER_KYC_DELETED			= -6
	FAIL_BY_BILLING						= -5
	FAIL_BY_SERVICE_TEMPORARY_NOT_VALID	= -4
	FAIL_BY_ACCESS_DENIED				= -3
	FAIL_BY_TOKEN_EXPIRED				= -2
	FAIL_BY_TOKEN_INVALID				= -1
	SUCCESS								= 0